# Generated by Django 4.2 on 2024-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='question_paper_no',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
